images: 2
path: '/home/andi/Sandbox/Nemodrive/nemodrive_scripts/points_select/images/'
log_file: '/home/andi/Sandbox/Nemodrive/nemodrive_scripts/points_select/points.yaml'
images_info:
  - tag: 'center_camera'
    file: '3FPSmarks-0.png'
  - tag: 'left_camera'
    file: '3FPSmarks-1.png'
