matching: 'manual'
#matching: 'combined'
#matching: 'learn_automatic_test_manual'
#matching: 'automatic'

c1:
  image: "images/train/3FPS_cf3e6de69c4d4e00-0.mov.png" #CENTER
  points:
    - [51, 279, '#1']
    - [56, 325, '#2']
    - [112, 274, '#3']
    - [112, 284, '#4']
    - [144, 287, '#5']
    - [148, 271, '#6']
    - [156, 278, '#7']
    - [158, 269, '#8']
    - [182, 265, '#9']
    - [207, 296, '#10']
    - [142, 330, '#11']
    - [224, 291, '#12']
    - [200, 322, '#13']
    - [165, 324, '#14']
    - [176, 324, '#15']
    - [194, 336, '#16']
    - [269, 272, '#17']
    - [319, 273, '#18']
    - [176, 227, '#19']
    - [186, 223, '#20']
    - [264, 252, '#21']
    - [264, 231, '#22']
    - [260, 230, '#23']
    - [273, 216, '#24']
    - [277, 216, '#25']
    - [288, 249, '#26']
    - [328, 259, '#27']
    - [321, 248, '#28']
    - [304, 243, '#29']
    - [370, 307, '#30']
    - [263, 289, '#31']
    - [405, 298, '#32']
    - [396, 297, '#33']
    - [469, 318, '#34']
    - [437, 287, '#35']
    - [419, 268, '#36']
    - [402, 252, '#37']
    - [392, 243, '#38']
    - [385, 234, '#39']
    - [289, 200, '#40']
    - [294, 194, '#41']
    - [298, 189, '#42']
    - [335, 178, '#43']
    - [311, 175, '#44']
    - [257, 193, '#41 prim left']

c2:
  image: "images/train/3FPS_cf3e6de69c4d4e00-1.mov.png" #LEFT
  points:
    - [74, 268, '#1']
    - [91, 312, '#2']
    - [136, 264, '#3']
    - [139, 273, '#4']
    - [173, 278, '#5']
    - [177, 263, '#6']
    - [188, 270, '#7']
    - [182, 262, '#8']
    - [223, 257, '#9']
    - [239, 292, '#10']
    - [179, 322, '#11']
    - [256, 287, '#12']
    - [233, 316, '#13']
    - [202, 317, '#14']
    - [215, 317, '#15']
    - [230, 329, '#16']
    - [302, 271, '#17']
    - [351, 274, '#18']
    - [193, 224, '#19']
    - [203, 217, '#20']
    - [292, 250, '#21']
    - [285, 230, '#22']
    - [279, 230, '#23']
    - [290, 216, '#24']
    - [294, 216, '#25']
    - [311, 248, '#26']
    - [356, 262, '#27']
    - [344, 248, '#28']
    - [327, 245, '#29']
    - [407, 310, '#30']
    - [400, 294, '#31']
    - [441, 305, '#32']
    - [431, 305, '#33']
    - [512, 329, '#34']
    - [473, 297, '#35']
    - [451, 276, '#36']
    - [431, 259, '#37']
    - [420, 249, '#38']
    - [409, 239, '#39']
    - [303, 200, '#40']
    - [308, 195, '#41']
    - [312, 189, '#42']
    - [347, 181, '#43']
    - [322, 176, '#44']
    - [369, 190, '#41 prim left']

#c1:
#  image: "images/1543056914.68_camera_3_off_181ms.jpg" #LEFT
#  points:
#    - [1392, 442, '#1 bulls eye']
#    - [428, 312, '#2 felinar stanga']
#    - [1540, 96, '#3 felinar dreapta']
#    - [1241, 302, '#4 felinar centru-dreapta']
#    - [726, 872, '#5 varful (cel apropiat de camera) pixului de pe caiet de pe cutie']
#    - [1007, 532, '#6 varful metrului intins pe axa masinii (la bordura din fata)']
#    - [1693, 292, '#7 varful stanga-sus al panoului Precis']
#    - [1691, 418, '#8 varful stanga-jos al panoului Precis']
#    - [1610, 414, '#9 varful stanga-sus al panoului publicitar din strada']
#    - [1609, 470, '#10 varful stanga-jos al panoului publicitar din strada']
#    - [767, 493, '#11 cosul casei indepartate']
#    - [437, 695, '#12 intersectia liniilor din beton (cativa metrii in stanga capacului de canal)']
#    - [965, 698, '#13 gaura capac canal apropiat (scobitura folosita pentr a-l ridica)']
#    - [1122, 339, '#14 colt stanga-jos al geamului din blocul din fata (ultimul etaj, a doua de la dreapta)']
#    - [1122, 320, '#15 colt stanga-sus al geamului din blocul din fata (ultimul etaj, a doua de la dreapta)']
#    - [1145, 339, '#16 colt dreapta-jos al geamului din blocul din fata (ultimul etaj, a doua de la dreapta)']
#    - [1147, 320, '#17 colt dreapta-sus al geamului din blocul din fata (ultimul etaj, a doua de la dreapta)']
#    - [800, 502, '#18 sigla Renault pentru Symbolul din fata']
#    - [903, 500, '#19 sigla Dacia pentru Loganul din fata']
#    - [1344, 1018, '#20 hood bump stanga']
#    - [1821, 1003, '#20 hood bump drepta']
#    - [685, 904, '#21 punctul din mijloc (din cele 3 linii cu puncte in capat de pe cutie)']
#    - [1106, 1002, '#22 "capul" L-ului de pe capota (din "ELECTRIC")']
#    - [109, 38, '#23 punctul cel mai inalt (ramura din dreapta din cele 2 la fel de inalte) ale copacului din extremitate stanga']
#    - [55, 517, '#24 sigla Dacia pentru Loganul din extrema stanga, dupa gard, parcat cu fata spre camera']
#    - [236, 504, '#25 sigla Wolwasgen alb stanga']
#    - [707, 505, '#26 sigla masina alba de langa Renault']
#    - [625, 918, '#27 punctul din textul "3.0" de pe cutie']
#    - [1266, 774, '#28 pietricica de la 4 m in fata masina, langa bordura stanga (foarte obscura)']
#    - [1779, 811, '#29 umbra frunzei in forma de semiluna de pe trotuarul din stanga, langa zona un gasonul intra pe trotuar']
#    - [813, 904, '#30 centrul turbinei din patratica cea mai de sus de pe cutie']
#    - [843, 848, '#31 coltul de pe cartonul de jos (bottom) orientat catre capacul de canalizare al cutiei']
#    - [548, 896, '#32 coltul de pe cartonul de sus (flaps) stanga-jos (in imagine) al cutiei']

#c2:
#  image: "images/1543056914.68_camera_3_off_181ms.jpg" #CENTER
#  points:
#    - [1278, 458, '#1 bulls eye']
#    - [370, 331, '#2 felinar stanga']
#    - [1420, 116, '#3 felinar dreapta']
#    - [1171, 318, '#4 felinar centru-dreapta']
#    - [464, 903, '#5 varful (cel apropiat de camera) pixului de pe caiet de pe cutie']
#    - [961, 543, '#6 varful metrului intins pe axa masinii (la bordura din fata)']
#    - [1613, 304, '#7 varful stanga-sus al panoului Precis']
#    - [1613, 426, '#8 varful stanga-jos al panoului Precis']
#    - [1557, 422, '#9 varful stanga-sus al panoului publicitar din strada']
#    - [1555, 476, '#10 varful stanga-jos al panoului publicitar din strada']
#    - [739, 451, '#11 cosul casei indepartate']
#    - [338, 714, '#12 intersectia liniilor din beton (cativa metrii in stanga capacului de canal)']
#    - [859, 713, '#13 gaura capac canal apropiat (scobitura folosita pentr a-l ridica)']
#    - [1084, 351, '#14 colt stanga-jos al geamului din blocul din fata (ultimul etaj, a doua de la dreapta)']
#    - [1084, 333, '#15 colt stanga-sus al geamului din blocul din fata (ultimul etaj, a doua de la dreapta)']
#    - [1107, 351, '#16 colt dreapta-jos al geamului din blocul din fata (ultimul etaj, a doua de la dreapta)']
#    - [1108, 333, '#17 colt dreapta-sus al geamului din blocul din fata (ultimul etaj, a doua de la dreapta)']
#    - [754, 515, '#18 sigla Renault pentru Symbolul din fata']
#    - [856, 512, '#19 sigla Dacia pentru Loganul din fata']
#    - [716, 1076, '#20 hood bump stanga']
#    - [1202, 1066, '#20 hood bump drepta']
#    - [417, 937, '#21 punctul din mijloc (din cele 3 linii cu puncte in capat de pe cutie)']
#    - [543, 1056, '#22 "capul" L-ului de pe capota (din "ELECTRIC")']
#    - [68, 59, '#23 punctul cel mai inalt (ramura din dreapta din cele 2 la fel de inalte) ale copacului din extremitate stanga']
#    - [17, 534, '#24 sigla Dacia pentru Loganul din extrema stanga, dupa gard, parcat cu fata spre camera']
#    - [192, 521, '#25 sigla Wolwasgen alb stanga']
#    - [661, 519, '#26 sigla masina alba de langa Renault']
#    - [356, 949, '#27 punctul din textul "3.0" de pe cutie']
#    - [1124, 788, '#28 pietricica de la 4 m in fata masina, langa bordura stanga (foarte obscura)']
#    - [1604, 824, '#29 umbra frunzei in forma de semiluna de pe trotuarul din stanga, langa zona un gasonul intra pe trotuar']
#    - [546, 935, '#30 centrul turbinei din patratica cea mai de sus de pe cutie']
#    - [597, 876, '#31 coltul de pe cartonul de jos (bottom) orientat catre capacul de canalizare al cutiei']
#    - [281, 928, '#32 coltul de pe cartonul de sus (flaps) stanga-jos (in imagine) al cutiei']
