images: 2
path: 'images/train/'
log_file: 'config/selection_points_initial.yaml'
images_info:
  - tag: 'center_camera'
    file: '3FPS_cf3e6de69c4d4e00-0.mov.png'
  - tag: 'left_camera'
    file: '3FPS_cf3e6de69c4d4e00-1.mov.png'
