c1:
  image: images/train/3FPS_cf3e6de69c4d4e00-0.mov.png
  points:
  - [466, 321, '#0']
  - [165, 324, '#1']
  - [11, 342, '#2']
  - [260, 231, '#3']
  - [331, 179, '#4']
  - [311, 175, '#5']
  - [257, 192, '#6']
  wat_image: '#center_camera'
c2:
  image: images/train/3FPS_cf3e6de69c4d4e00-1.mov.png
  points:
  - [510, 331, '#0']
  - [203, 317, '#1']
  - [45, 327, '#2']
  - [280, 230, '#3']
  - [344, 181, '#4']
  - [322, 176, '#5']
  - [269, 190, '#6']
  wat_image: '#left_camera'
matching: manual
